### ISSUE TITLE
RA v3 is expecting X-TOTAL-COUNT header

### ISSUE THREAD

**Issue by paullyFIRE** [lalalilo/ra-express-sequelize-backend#9]
From RA v3 - I get the following error:
**_The X-Total-Count header is missing in the HTTP Response. The jsonServer Data Provider expects responses for lists of resources to contain this header with the total number of results to build the pagination. If you are using CORS, did you declare X-Total-Count in the Access-Control-Expose-Headers header?_**

Server side, I've enabled CORS to expose the header, but doesn't seem like your package is adding it to the getList and getManyReference actions - required/specified in this doc:
[https://github.com/marmelab/react-admin/blob/master/packages/ra-data-json-server/README.md#rest-dialect](https://github.com/marmelab/react-admin/blob/master/packages/ra-data-json-server/README.md#rest-dialect)

Am I missing something or is this something you need to add?

Big thanks - and promising package.

**Comment by paullyFIRE** [comment]
Can confirm just added the below within the getList function to get it working:
```
...
res.set('Content-Range', from + "-" + (from + rows.length) + "/" + count);
res.set('X-TOTAL-COUNT', rows.length);
...
```

**Comment by nicgirault** [comment]
Thanks @paullyFIRE for reporting this issue. Actually the lib is compatible with react-admin v2 where the expected header is `content-range`. We will release a new version in the following days.

**Comment by nicgirault** [comment]
Actually I upgraded to v3 and there is no problem with the current version of the backend. This lib is currently working with https://github.com/marmelab/react-admin/tree/master/packages/ra-data-simple-rest and not https://github.com/marmelab/react-admin/tree/master/packages/ra-data-json-server. Nevertheless I will see what it involves to make it compatible with ra-data-json-server.

**Comment by paullyFIRE** [comment]
Hey @nicgirault ,

Thanks for the quick reply - really appreciate that.

You're 100% correct regarding the two dataProviders. I recently dropped into the RA ecosystem, so it was my mistake to raise this issue so hastily - sorry about that.

Will switch to **ra-data-simple-rest** and give it a crack.
